from PySide6.QtGui import QColor, QPalette

q_palette = QPalette()
# TODO: prefers_color_scheme ['light','dark','no-preference']
q_palette.setColor(QPalette.ColorRole.WindowText, QColor("#ffffff"))
q_palette.setColor(QPalette.ColorRole.Button, QColor("#353535"))
# q_palette.setColor(QPalette.ColorRole.Light, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.Midlight, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.Dark, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.Mid, QColor("#ff0000"))
q_palette.setColor(QPalette.ColorRole.Text, QColor("#ffffff"))
# q_palette.setColor(QPalette.ColorRole.BrightText, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.ButtonText, QColor("#ffffff"))
q_palette.setColor(QPalette.ColorRole.Base, QColor("#3b3b3b"))
q_palette.setColor(QPalette.ColorRole.Window, QColor("#2b2b2b"))
# q_palette.setColor(QPalette.ColorRole.Shadow, QColor("#ff0000"))
q_palette.setColor(QPalette.ColorRole.Highlight, QColor("#2979ff"))
q_palette.setColor(QPalette.ColorRole.HighlightedText, QColor("#ffffff"))
# q_palette.setColor(QPalette.ColorRole.Link, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.LinkVisited, QColor("#ff0000"))
q_palette.setColor(QPalette.ColorRole.AlternateBase, QColor("#2b2b2b"))
# q_palette.setColor(QPalette.ColorRole.NoRole, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.ToolTipBase, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.ToolTipText, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.PlaceholderText, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.Accent, QColor("#ff0000"))
# q_palette.setColor(QPalette.ColorRole.NColorRoles, QColor("#ff0000"))
