name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build app
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2019]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Install dependencies for ${{ matrix.os }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with pyinstaller for ${{ matrix.os }}
        run: pyinstaller --noconfirm --clean --onefile --name="kudan" --icon="icon.png" --add-data="icon.png:." --add-data="font:font" --windowed src/main.py

      - name: Rename builded app
        run: mv ./dist ./dist-${{ matrix.os }}

      - name: Upload result job ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: kudan-pyinstaller-artifact
          path: ./dist*

  upload:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: kudan-pyinstaller-artifact

      - name: Zip file windows
        run: zip -r kudan_windows.zip dist-windows-*

      - name: Zip file ubuntu
        run: zip -r kudan_linux.zip dist-ubuntu-*

      - name: Zip file macos
        run: zip -r kudan_macos.zip dist-macos-*

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            kudan_windows.zip
            kudan_linux.zip
            kudan_macos.zip
